version: "3.8"

services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    env_file: ./API/.env
    environment:
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    volumes:
      - db:/var/lib/postgres
  api:
    depends_on:
      - postgresdb
    build:
      context: ./
      dockerfile: dockerfile.api
    restart: unless-stopped
    env_file: ./API/.env
    command: sh -c "npm run run:migrations && npm run build && npm run start"
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
  app:
    build:
      context: ./
      dockerfile: dockerfile.app
    working_dir: /todo/APP
    command: serve -s dist -l 3001
    ports:
      - "3001:3001"
    depends_on:
      - api

volumes:
  db:
